# Unified Application Configuration
application:
  name: DevOpsSimulator
  version: 2.0.0
  environment: production

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  # Experimental: multi-port testing (disabled by default)
  # multi_port: [9000, 9001, 9002]

logging:
  level: INFO
  format: json
  output: /var/log/app.log
  # Experimental: structured logging with AI analysis
  # ai_analysis: enabled

database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod
  # Experimental: distributed DB cluster support
  # distributed: true

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true
  # Experimental: advanced/AI-optimized features
  # chaos_engineering: enabled
  # experimental_features: false

# Optional: AI feature flags (disabled in production)
ai_features:
  predictive_scaling: false
  anomaly_detection: false
  auto_optimization: false
  # model_version: "v2.1.0"

# Keep experimental providers commented
# cloud_providers:
#   - aws
#   - azure
#   - gcp
#   - digitalocean

# Security (production)
security:
  zero_trust: enabled
  encryption: AES-256
  audit_logging: basic
